# Generated by Django 5.2.9 on 2025-12-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_type',
            field=models.CharField(choices=[('movie', '電影'), ('tv', '影集')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
