# Generated by Django 5.2.9 on 2026-01-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_movie_poster_url_alter_movie_poster_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='評分'),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='status',
            field=models.CharField(choices=[('plan', '想看'), ('watching', '觀看中'), ('watched', '已看完'), ('dropped', '棄劇')], default='plan', max_length=10, verbose_name='狀態'),
        ),
    ]
