# Generated by Django 5.2.9 on 2026-01-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usermovie_rating_usermovie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='觀影心得'),
        ),
    ]
