# Generated by Django 5.2.9 on 2026-01-16 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usermovie_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermovie',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='media_type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermovie',
            name='tmdb_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], null=True, verbose_name='評分'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='status',
            field=models.CharField(choices=[('watchlist', '待看清單'), ('watching', '觀看中'), ('watched', '已看完'), ('dropped', '棄劇')], default='watchlist', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usermovie',
            name='movie',
        ),
    ]
